version: "3.12.3-bookworm"
services:
  projecto:
    build: .
    ports:
      - "8000:8000"
    links:
      - mysqlito
 
  mysqlito:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=projecto
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data:
