# Generated by Django 5.0.4 on 2024-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('Comentario', models.TextField(max_length=500)),
                ('EDAD', models.TextField(max_length=3)),
                ('Email', models.EmailField(max_length=500)),
                ('calificacion', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
    ]
