# Generated by Django 5.0.4 on 2024-07-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradatexto', '0002_rename_edad_formulario_edad_formulario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
